name: Validate Sprint - Configurável

on:
  workflow_call:
    inputs:
      config_path:
        description: 'Caminho para o arquivo de configuração YAML'
        required: false
        type: string
        default: 'cursos/sistemas-informacao/M07/config/validation-config.yml'
      module:
        description: 'Módulo a ser validado (M01-M12)'
        required: false
        type: string
        default: 'M07'
      course:
        description: 'Curso a ser validado'
        required: false
        type: string
        default: 'sistemas-informacao'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código do repositório atual
        uses: actions/checkout@v3
        
      - name: Checkout dos templates CI/CD
        uses: actions/checkout@v3
        with:
          repository: Inteli-College/ci-cd-templates
          path: ci-cd-templates

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: List full directory tree
        run: tree -a || find . -type d -name ".git" -prune -o -print | sed 's|[^/]*/|  |g'

      - name: Instalar dependências
        run: pip install -r ci-cd-templates/shared/requirements.txt

      - name: Verificar arquivo de configuração
        run: |
          cd ci-cd-templates
          CONFIG_PATH="${{ inputs.config_path }}"
          echo "📋 Usando configuração: $CONFIG_PATH"
          
          if [ ! -f "$CONFIG_PATH" ]; then
            echo "❌ Arquivo de configuração não encontrado: $CONFIG_PATH"
            echo "🔧 Criando configuração padrão para ${{ inputs.course }}/${{ inputs.module }}"
            
            # Criar configuração usando template se não existir
            mkdir -p $(dirname "$CONFIG_PATH")
            PYTHONPATH=. python shared/utils/create_default_config.py "$CONFIG_PATH" "${{ inputs.course }}" "${{ inputs.module }}"
          else
            echo "✅ Arquivo de configuração encontrado"
          fi

      - name: Executar validações configuráveis
        run: |
          cd ci-cd-templates
          PYTHONPATH=. VALIDATION_CONFIG="${{ inputs.config_path }}" python cursos/sistemas-informacao/M07/scripts/validation_engine.py

      - name: Postar resultado no Slack (se configurado)
        if: always()
        run: |
          cd ci-cd-templates
          echo "📢 Enviando notificação para o Slack (se configurado)"
          PYTHONPATH=. VALIDATION_CONFIG="${{ inputs.config_path }}" python shared/post_slack.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
